server:
  port: 6200
  contextPath: /tng-vnv-tee
spring.jackson.property-naming-strategy: SNAKE_CASE
api:
  name: 5GTANGO VnV Platform Test Execution Engine
  description: An H2020 5GTANGO project
  version: 0.0.1
  host: tng-vnv-tee:6200
  terms.url: https://5gtango.eu/
  license:
    name: Apache License 2.0
    url: https://github.com/sonata-nfv/tng-vnv-tee/blob/master/LICENSE
app:
  tee.tmp.dir: /workspace
  gk:
    host: gk
    base.url: http://${app.gk.host}:32001/api/v2
    session:
      endpoint: ${app.gk.base.url}/sessions
      username: sonata
      password: 1234
  catalogue:
    host: tng-vnv-catalogue
    base.url: http://${app.catalogue.host}:6200
    test.suite.load.endpoint: ${app.catalogue.base.url}/test-suites/{testSuiteId}
    resource.download.endpoint: ${app.catalogue.base.url}/test-suites/{testSuiteId}/download-resource?source={source}
  trr:
    host: tng-vnv-trr
    base.url: http://${app.trr.host}:6300
    test.suite.result.create.endpoint: ${app.trr.base.url}/test-suite-results
    test.suite.result.update.endpoint: ${app.trr.base.url}/test-suite-results/{testSuiteResultId}
    network.service.instance.load.endpoint: ${app.trr.base.url}/network-service-instance-instances/{networkServiceInstanceId}
