server:
  port: 6200
  contextPath: /tng-vnv-tee
app:
  tee.tmp.dir: /docker-host-shared-tmp
  gk:
    host: gk
    base.url: http://${app.gk.host}:32001/api/v2
    session:
      endpoint: ${app.gk.base.url}/sessions
      username: sonata
      password: 1234
  catalogue:
    host: tng-vnv-catalogue
    base.url: http://${app.catalogue.host}:6200
    test.suite.load.endpoint: ${app.catalogue.base.url}/test-suites/{testSuiteId}
    resource.download.endpoint: ${app.catalogue.base.url}/test-suites/{testSuiteId}/download-resource?source={source}
  trr:
    host: tng-vnv-trr
    base.url: http://${app.trr.host}:6300
    test.suite.result.create.endpoint: ${app.trr.base.url}/test-suite-results
    test.suite.result.update.endpoint: ${app.trr.base.url}/test-suite-results/{testSuiteResultId}
    network.service.instance.load.endpoint: ${app.trr.base.url}/network-service-instance-instances/{networkServiceInstanceId}
