server:
  port: 6200
  contextPath: /tng-vnv-tee
spring.jackson.property-naming-strategy: SNAKE_CASE
api:
  name: 5GTANGO VnV Platform Test Execution Engine
  description: An H2020 5GTANGO project
  version: 0.0.1
  host: tng-vnv-tee:6200
  terms.url: https://5gtango.eu/
  license:
    name: Apache License 2.0
    url: https://github.com/sonata-nfv/tng-vnv-tee/blob/master/LICENSE
app:
  tee.tmp.dir: /workspace
  gk:
    host: gk
    base.url: http://qual-sp-bcn.5gtango.eu:32001/api/v2
    session:
      endpoint: ${app.gk.base.url}/sessions
      username: sonata
      password: 1234
  vnvgk:
    host: gk
    base.url: http://pre-int-vnv-bcn.5gtango.eu:32002/api/v3
  cat:
    host: tng-cat
    base.url: http://${app.cat.host}:4011/api/catalogues/v2
    package.metadata.endpoint: ${app.vnvgk.base.url}/packages/{packageId}
    test.metadata.endpoint: ${app.cat.base.url}/tests/{testUuid}
    test.suite.load.endpoint: ${app.cat.base.url}/test-suites/{testSuiteId}
    resource.download.endpoint: ${app.vnvgk.base.url}/packages/{packageId}/files/{resourceUuid}
  trr:
    host: tng-rep
    base.url: http://${app.trr.host}:4012/trr
    test.suite.result.create.endpoint: ${app.trr.base.url}/test-suite-results
    test.suite.result.update.endpoint: ${app.trr.base.url}/test-suite-results/{uuid}
    network.service.instance.load.endpoint: ${app.gk.base.url}/records/services/{networkServiceInstanceId}
    network.function.instance.load.endpoint: ${app.gk.base.url}/records/functions/{networkFunctionInstanceId}
